---
title: "Manuscript"
date: "`r Sys.Date()`"
output:
  bookdown::html_notebook2:
    code_folding: hide
    df_print: paged
    toc: yes
    toc_float:
      toc_collapsed: yes
    toc_depth: 3
    number_sections: no
    theme: paper
    highlight: textmate
  bookdown::word_document2:
    # see https://bookdown.org/yihui/rmarkdown-cookbook/word-template.html for how to customise word output with a template docx
    reference_docx: word-styles-reference-01.docx
    number_sections: no
    toc: no
  bookdown::pdf_document2:
    latex_engine: xelatex
    keep_tex: true
    toc: yes
    geometry: "left=4cm, right=3cm, top=2.5cm, bottom=2.5cm"
bibliography: references.bib
csl: nature.csl
link-citations: true
always_allow_html: true
editor_options: 
  chunk_output_type: console
---

```{r setup, global-options, results="hide", echo=ifelse(knitr::is_html_output(), yes=TRUE, no=FALSE), message=FALSE, warning=FALSE}
knitr::opts_chunk$set(warning=FALSE, message=FALSE, echo=ifelse(knitr::is_html_output(), yes=TRUE, no=FALSE),
                      tab.cap.pre = "", tab.cap.sep = "")
library(targets)

source(file.path("code", "utils.R"))

# captions
caps <- tar_read(figure_table_captions)
```

**Authors:**

First Author^1^, Last Author\*

\* Corresponding author. 

**Affiliations:**

1.  Somewhere 1
2.  Somewhere 2

**Correspondence:** Last author (email: [l.author\@ucl.ac.uk](mailto:l.author\@ucl.ac.uk){.email})

Address

Postcode

**Running title:** Manuscript

\newpage

------------------------------------------------------------------------

# Abstract

**Background/Objectives:** This study aims to...

**Methods:** Study design, statistics etc...

**Results:** Important findings...

**Conclusions:** Take home messages...

\newpage

------------------------------------------------------------------------

# Introduction

Important background.

\newpage

------------------------------------------------------------------------

# Methods

## Study population

Details...

## Statistical analysis

Statistical analysis was performed using R (R for GNU macOS, Version 4.2.0, The R Foundation for Statistical Computing, Vienna, Austria). R packages used included targets, tarchetypes, workflowr, tidyverse, knitr, gtsummary and flextable.[@targets; @tarchetypes; @workflowr; @tidyverse; @knitr; @gtsummary; @flextable]

\newpage

------------------------------------------------------------------------

# Results

Findings...

Cite a figure: `r caps$main_figure('plot1', display = 'cite')`.

\newpage

------------------------------------------------------------------------

# Discussion

Discuss findings...

## Strengths and limitations

Limitations included... but that's ok because of the following strengths...

## Conclusions

Take home messages...

\newpage

------------------------------------------------------------------------

# Acknowledgements

We gratefully acknowledge...

# Conflict of Interest

Any competing interests...

# Financial support

Funders and grant numbers

# Authors' contributions

Who did what

# Data availability statement

The data and code used to generate results/figures are available at...

\newpage

------------------------------------------------------------------------

# References

<!-- Need this to insert references before end of document -->
<div id="refs"></div>

\newpage

------------------------------------------------------------------------

# Figure legends

`r bold_cap(caps$main_figure('plot1'))`

`r bold_cap(caps$supplementary_figure('plot2'))`

# Table legends

`r bold_cap(caps$main_table('table1'))`

`r bold_cap(caps$supplementary_table('table2'))`
