---
title: "Home"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
    code_folding: hide
editor_options:
  chunk_output_type: console
---

```{r setup, global-options, results="hide", echo=ifelse(knitr::is_html_output(), yes=TRUE, no=FALSE), message=FALSE, warning=FALSE}
knitr::opts_chunk$set(warning=FALSE, message=FALSE, echo=ifelse(knitr::is_html_output(), yes=TRUE, no=FALSE),
                      tab.cap.pre = "", tab.cap.sep = "")
library(targets)
library(ourproj)
```

Welcome to my research website.

# Target dependencies

```{r}
# for demonstration
tar_load(summary)
```

# Manuscript

- Manuscript text
  - [html](manuscript.nb.html){target="_blank"}
  - [MS Word](manuscript.docx){target="_blank"}
- Manuscript tables
  - [html](tables.html){target="_blank"}
  - [MS Word](tables.docx){target="_blank"}
- Manuscript figures
  - [html](figures.html){target="_blank"}
  - [pdf](figures.pdf){target="_blank"}
  
# Targets

```{r}
targets::tar_visnetwork(targets_only = TRUE,
                        names = WFLWR_INDEX_RMD,
                        callr_arguments = list(show = FALSE))
```

# Workflowr reports

```{r}
tar_read(WFLWR_RMDS_REACTABLE)
```
